import Foundation

/// A compressed structural overview of an entire book — the "Repomap" for literature.
///
/// Adapted from Karpathy's Repomap concept for codebases: gives an LLM
/// "peripheral vision" over the entire book without reading every page.
/// Typically 500-1500 tokens when serialized, fitting comfortably in any prompt.
public struct BookRepomap: Sendable, Codable {
    public let title: String
    public let author: String?
    public let language: String?
    public let spineCount: Int

    /// Hierarchical sections with summaries (generated by LLM on import).
    public let sections: [SectionNode]

    /// Key recurring entities across the whole book.
    public let globalEntities: [NamedEntity]

    /// High-level classification (genre, themes, cultural context).
    public let classification: BookClassification?

    public init(
        title: String,
        author: String? = nil,
        language: String? = nil,
        spineCount: Int,
        sections: [SectionNode] = [],
        globalEntities: [NamedEntity] = [],
        classification: BookClassification? = nil
    ) {
        self.title = title
        self.author = author
        self.language = language
        self.spineCount = spineCount
        self.sections = sections
        self.globalEntities = globalEntities
        self.classification = classification
    }

    // MARK: - Section Node

    /// A TOC section with its LLM-generated summary and entity index.
    public struct SectionNode: Sendable, Codable, Identifiable {
        public let id: UUID
        public let title: String
        public let level: Int
        /// 1-2 sentence LLM-generated summary of this section's content.
        public let summary: String
        /// Entities introduced or discussed in this section.
        public let keyEntities: [String]
        /// Range of chunk global indices that fall within this section.
        public let chunkRange: ChunkRange
        /// Child sections (for hierarchical display).
        public let children: [SectionNode]

        public init(
            id: UUID = UUID(),
            title: String,
            level: Int = 0,
            summary: String = "",
            keyEntities: [String] = [],
            chunkRange: ChunkRange = ChunkRange(start: 0, end: 0),
            children: [SectionNode] = []
        ) {
            self.id = id
            self.title = title
            self.level = level
            self.summary = summary
            self.keyEntities = keyEntities
            self.chunkRange = chunkRange
            self.children = children
        }
    }

    /// A range of chunk indices. Uses explicit struct instead of `Range<Int>` for Codable.
    public struct ChunkRange: Sendable, Codable, Hashable {
        public let start: Int
        public let end: Int

        public init(start: Int, end: Int) {
            self.start = start
            self.end = end
        }

        public var count: Int { max(end - start, 0) }
        public var range: Range<Int> { start..<end }
    }

    // MARK: - Named Entity

    /// A recurring entity (person, place, concept, term) tracked across the book.
    public struct NamedEntity: Sendable, Codable, Identifiable {
        public let id: UUID
        public let name: String
        public let type: EntityType
        /// Global chunk index where this entity first appears.
        public let firstAppearanceChunk: Int
        /// 1-sentence description of this entity's role in the book.
        public let significance: String

        public init(
            id: UUID = UUID(),
            name: String,
            type: EntityType,
            firstAppearanceChunk: Int = 0,
            significance: String = ""
        ) {
            self.id = id
            self.name = name
            self.type = type
            self.firstAppearanceChunk = firstAppearanceChunk
            self.significance = significance
        }

        public enum EntityType: String, Codable, Sendable {
            case person
            case place
            case concept
            case term
            case organization
            case event
            case work  // Referenced books, artworks, etc.
        }
    }

    // MARK: - Book Classification

    /// High-level book classification for prompt context.
    public struct BookClassification: Sendable, Codable {
        public let hierarchyPath: String  // e.g. "Fiction > Literary > Russian Literature"
        public let themes: [String]
        public let culturalContext: String?
        public let estimatedDifficulty: String?  // e.g. "Advanced", "Intermediate"

        public init(
            hierarchyPath: String = "",
            themes: [String] = [],
            culturalContext: String? = nil,
            estimatedDifficulty: String? = nil
        ) {
            self.hierarchyPath = hierarchyPath
            self.themes = themes
            self.culturalContext = culturalContext
            self.estimatedDifficulty = estimatedDifficulty
        }
    }

    // MARK: - Serialization for Prompts

    /// Compact text representation suitable for injection into an LLM prompt.
    /// Typically 500-1500 tokens.
    public func promptSerialization() -> String {
        var lines: [String] = []
        lines.append("# Book: \(title)")
        if let author { lines.append("Author: \(author)") }
        if let language { lines.append("Language: \(language)") }
        lines.append("Spine items: \(spineCount)")

        if let cls = classification {
            lines.append("Genre: \(cls.hierarchyPath)")
            if !cls.themes.isEmpty {
                lines.append("Themes: \(cls.themes.joined(separator: ", "))")
            }
            if let ctx = cls.culturalContext {
                lines.append("Cultural context: \(ctx)")
            }
        }

        if !globalEntities.isEmpty {
            lines.append("\n## Key Entities")
            for entity in globalEntities.prefix(20) {
                lines.append("- \(entity.name) (\(entity.type.rawValue)): \(entity.significance)")
            }
        }

        if !sections.isEmpty {
            lines.append("\n## Structure")
            for section in sections {
                appendSectionLines(section, into: &lines)
            }
        }

        return lines.joined(separator: "\n")
    }

    private func appendSectionLines(_ section: SectionNode, into lines: inout [String]) {
        let indent = String(repeating: "  ", count: section.level)
        var line = "\(indent)- \(section.title)"
        if !section.summary.isEmpty {
            line += ": \(section.summary)"
        }
        lines.append(line)
        for child in section.children {
            appendSectionLines(child, into: &lines)
        }
    }
}
